(function(){
'use strict';
const main=document.getElementById('main-content');
const params=new URLSearchParams(location.search);
let state=params.get('state')||'normal', zoom=params.get('text')==='200'?2:1, current='', origin='news', newsFilter='all', themeFilter='all', laneFilter='all', decisionFilter='all', chartPeriod=20, chartIndex=59, guideStep=0;
const positions={}, readArticles=new Set();
const ASOF='10/09 장 마감 · 가상 자료';
const themes=[
 {id:'chip',name:'반도체 장비',prev:1,rank:1,old:7,now:6,moneyOld:1.6,money:1.2,trend:'steady',reason:'설비 투자와 장비 수요에 대한 관심이 이어지는 상황입니다.',next:'실제 수주와 회사 전망이 이어지는지 확인합니다.',stocks:['a']},
 {id:'mlcc',name:'MLCC',prev:2,rank:2,old:3,now:3,moneyOld:1.1,money:1.1,trend:'steady',reason:'수요 회복을 확인하려는 관심이 이어지는 상황입니다.',next:'회사별 가동률과 실적 발표를 확인합니다.',stocks:[]},
 {id:'ai',name:'AI 소프트웨어',prev:3,rank:3,old:4,now:4,moneyOld:1.2,money:1.2,trend:'steady',reason:'서비스 도입 소식이 이어지는 상황입니다.',next:'유료 고객과 매출로 이어지는지 확인합니다.',stocks:[]},
 {id:'robot',name:'로봇 부품',prev:4,rank:4,old:2,now:2,moneyOld:1.1,money:1.1,trend:'steady',reason:'부품 공급 확대를 관찰하는 상황입니다.',next:'계약 규모와 실제 공급 회사를 확인합니다.',stocks:[]},
 {id:'material',name:'반도체 소재',prev:5,rank:5,old:2,now:2,moneyOld:1.0,money:1.0,trend:'steady',reason:'소재 수요에 대한 보도가 이어지는 상황입니다.',next:'증설 시점과 고객사 채택 여부를 확인합니다.',stocks:[]},
 {id:'grid',name:'전력망',prev:8,rank:6,old:2,now:5,moneyOld:1.1,money:1.4,trend:'rising',reason:'전력 설비 투자와 납기 관련 새 사건이 늘어난 상황입니다.',next:'투자 발표가 해당 회사의 수주로 연결되는지 확인합니다.',stocks:['b']},
 {id:'cooling',name:'데이터센터 냉각',prev:14,rank:9,old:1,now:4,moneyOld:0.8,money:1.3,trend:'rising',reason:'냉각 설비 관련 사건과 돈몰림이 늘었지만 아직 TOP6 밖에 있습니다.',next:'공급 계약과 실제 돈몰림이 함께 나타나는지 확인합니다.',stocks:['c']},
 {id:'defense',name:'방산',prev:6,rank:8,old:5,now:2,moneyOld:1.3,money:0.8,trend:'cooling',reason:'앞서 집중됐던 사건 보도가 줄어든 상황입니다.',next:'관심 감소와 실적 전망 악화를 구분해 확인합니다.',stocks:[]}
];
const stocks={a:{name:'가상기업 A',theme:'chip',lanes:['B','D'],prev:['B','D'],representative:true,offset:0},b:{name:'가상기업 B',theme:'grid',lanes:['C'],prev:['C'],representative:true,offset:220},c:{name:'가상기업 C',theme:'cooling',lanes:['D'],prev:[],representative:false,offset:430}};
stocks.h={name:'가상 보유기업 H',theme:'chip',lanes:[],prev:[],representative:false,offset:610};
const candidateIds=['a','b','c'];
const decisions={
 a:{status:'buy',label:'매수대상',headline:'종목 심사 통과 · 진입 가격 확인',reason:'시장행동과 실적 근거를 확인했습니다. 진입 가격을 살펴볼 대상입니다.',support:'B·D 레인과 반도체 장비 주도테마에 함께 포함된 가상 후보입니다. 심사 근거는 관련 뉴스와 함께 다시 확인합니다.',risk:'투자 발표가 실제 수주·매출로 이어지는 시점은 미확인입니다. 선 위의 가격만으로 새 매수 신호를 만들지 않습니다.',next:'트레이딩룸에서 회복·돌파 여부와 진입 기준 가격을 확인합니다.',timing:'매수대상이지만 새 회복·돌파 신호는 없는 예시입니다. 종목 선택과 지금 진입할지는 따로 확인합니다.'},
 b:{status:'hold',label:'보류',headline:'추가 근거를 기다리는 종목',reason:'전력망 관심과 돈몰림은 늘었지만 해당 회사의 추가 수주 근거는 부족합니다.',support:'C레인 후보이며 전력망 테마의 TOP6 진입을 함께 관찰합니다.',risk:'생산 일정 설명만으로 주문 증가나 실적 개선을 확정할 수 없습니다.',next:'회사 공시에서 추가 수주와 실적 근거를 확인합니다.',timing:'결정실 보류 상태입니다. 매수대상으로 넘어간 것처럼 표시하지 않고 차트는 참고로만 봅니다.'},
 c:{status:'not-input',label:'미입력',headline:'D레인 충족 · 아직 결정실 입력 전',reason:'D 조건은 충족했지만 운영 대표로 선정되지 않았습니다.',support:'TOP6 밖 돈몰림 추천테마의 D 단독 후보입니다. 후보 관찰 기록은 유지합니다.',risk:'결정실 판정이 없는 상태입니다. 미입력을 보류·제외·심사 통과로 해석하지 않습니다.',next:'D 운영 대표 선정 여부 또는 A·B·C 조건 충족을 확인합니다.',timing:'아직 종목 심사를 거치지 않았습니다. 차트 확인만으로 매수대상이 되지는 않습니다.'}
};
const articles=[
 {id:1,title:'가상기업 A, 장비 투자 계획 발표…실제 수주 규모는 후속 공시에서 확인',theme:'chip',time:'08:25',kind:'회사 발표',company:'a',summary:'가상기업 A가 설비 투자 계획을 발표한 상황입니다. 투자 발표와 매출 발생 시점은 구분해서 살펴봅니다.'},
 {id:2,title:'전력망 증설 논의 확대…변압기 공급 일정과 납기 변화에 관심',theme:'grid',time:'08:18',kind:'업종 참고',company:null,summary:'전력 설비 투자 논의가 늘어나는 상황입니다. 업종 기사만으로 특정 회사의 수주를 확정하지 않습니다.'},
 {id:3,title:'가상기업 C, 냉각 장치 실증 참여…본계약 체결 여부는 아직 미확인',theme:'cooling',time:'08:10',kind:'회사 발표',company:'c',summary:'실증 참여 소식의 예시입니다. 본계약의 규모·기간·매출 영향은 확인되지 않았습니다.'},
 {id:4,title:'가상기업 B, 전력 설비 생산 일정 설명…추가 수주 여부는 별도 확인 필요',theme:'grid',time:'07:58',kind:'회사 발표',company:'b',summary:'생산 일정 설명의 예시입니다. 생산능력 확대가 실제 주문 증가를 뜻하는지는 추가 확인이 필요합니다.'},
 {id:5,title:'반도체 장비 고객사의 투자 속도 조절 보도…업체별 영향은 엇갈릴 가능성',theme:'chip',time:'07:44',kind:'업종 참고',company:null,summary:'고객사 투자 속도 변화의 예시입니다. 업체별 고객 구성과 수주 잔고를 따로 확인합니다.'},
 {id:6,title:'데이터센터 전력·냉각 비용 논의 증가…관심 확대와 실제 자금 유입은 구분',theme:'cooling',time:'07:32',kind:'업종 참고',company:null,summary:'운영 비용에 대한 보도가 늘어난 예시입니다. 기사 증가 자체가 투자금 유입을 의미하지 않습니다.'},
 {id:7,title:'전력 설비 공급망 관련 보도…원문 확인과 회사 연결 검토가 진행 중',theme:'grid',time:'07:20',kind:'분석 대기',company:null,summary:'아직 기사 분석이 완료되지 않은 예시입니다. 제목은 전체 목록에 남기고 영향 판단은 보류합니다.'},
 {id:8,title:'방산 관련 새 보도 감소…기존 계약의 집행 일정은 계속 확인할 필요',theme:'defense',time:'07:05',kind:'업종 참고',company:null,summary:'새 보도가 줄어든 상황의 예시입니다. 보도량 감소를 실적 악화나 매도 신호로 바꾸지 않습니다.'}
];
const rooms=[['research','리서치센터','추천테마 · TOP6 · 구성 종목'],['manager','펀드매니저실','A·B·C·D 레인별 종목'],['park','사장실 놀이공원','전 거래일 대비 변화 · 주요 내용'],['news','뉴스룸','오늘 제목 전체 훑어보기'],['themes','테마뉴스','관심 변화 · 돈몰림 비교'],['trading','트레이딩룸','선택된 종목 · 매수 타이밍 · 보유 관리'],['decision','결정실','매수대상·보류·제외 · 종목별 판정'],['signals','BNF 신호실','기존 신호와 미충족 조건'],['records','기록','성과기록 · 선정성적']];
const guideLines=['오늘의 변화부터 함께 살펴볼까요?','TOP6는 종목이 아니라 테마 순위예요.','뉴스 관심과 실제 돈몰림을 함께 보세요.','한 종목에 여러 레인이 붙을 수 있어요.','결정실에서 골라도 매수 타이밍은 따로 봐요.'];
const aliases={welcome:'today',article:'article-1','article-b':'article-3',candidate:'chart-c',verification:'manager','holding-a':'chart-a','holding-b':'chart-b',chair:'park','decision-detail':'decision'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const theme=id=>themes.find(t=>t.id===id);
const star='<svg class="pixel-star" viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M6 0h4v4h4v2h2v4h-5v6H9v-3H7v3H5v-6H0V6h2V4h4z"/><path fill="#24363d" d="M5 6h2v2H5zm4 0h2v2H9z"/></svg>';
function decisionBadge(id){const d=decisions[id];return d?'<span class="status verdict-'+d.status+'">'+d.label+'</span>':'<span class="status muted">보유 관리</span>';}
function journey(stage,id){const items=[['news','뉴스'],['research','테마·돈몰림'],['manager','레인'],['decision','결정실'],[id?'chart-'+id:'trading','타이밍']];return '<nav class="journey" aria-label="확인 순서">'+items.map((x,i)=>'<a href="#'+x[0]+'"'+(i===stage?' aria-current="step"':'')+'>'+x[1]+'</a>').join('')+'</nav>';}
function decisionSummary(){return '<a class="decision-spotlight" href="#decision"><span class="spotlight-kicker">'+star+' 오늘의 결정실 · 가상 판정</span><b>매수대상 1 · 보류 1</b><span>미입력 1 · 종목별 이유와 다음 확인 <i aria-hidden="true">→</i></span></a>';}
function research(){return back('today','오늘로')+title('리서치센터 · 테마와 종목','돈이 모이는 곳에서<br>살펴볼 종목까지.','추천테마와 TOP6를 각각 보고, 구성 종목을 비교합니다.')+journey(1)+'<div class="notice"><b>가상 변화</b> · 전력망 8위 → 6위 진입 / 방산 6위 → 8위 이탈</div><section class="section"><h2>↗ 돈몰림 추천테마</h2><p class="meta">TOP6 밖에서 돈이 먼저 들어온 후보 · 가상 1개</p><a class="theme-card" href="#theme-cooling"><span class="status">↗ 추천테마 · TOP6 밖</span><h3>데이터센터 냉각</h3><p>돈몰림 0.8 → 1.3배 · 14 → 9위<br>가상기업 C · 테마 구성 종목</p><span class="card-action">추천 이유와 종목 보기 →</span></a></section><section class="section"><h2>★ TOP6 주도테마와 종목</h2><p class="meta">10/08 → 10/09 · 가상 장 마감 비교</p><ol class="rank-list">'+themes.filter(t=>t.rank<=6).map(t=>'<li><a href="#theme-'+t.id+'"><span class="rank-num">'+t.rank+'</span><span><b>'+t.name+'</b><small>'+(t.prev>6?'TOP6 신규 진입':'TOP6 유지')+' · 돈몰림 '+t.money.toFixed(1)+'배</small><small>'+(t.stocks.length?t.stocks.map(id=>stocks[id].name).join(' · '):'구성 종목 예시 미수록')+'</small></span><span class="rank-delta">종목 →</span></a></li>').join('')+'</ol></section><div class="related-actions"><a class="button secondary" href="#themes">뉴스 관심 변화와 비교</a><a class="button" href="#manager">A·B·C·D 레인 종목 확인</a></div><p class="meta section">추천테마와 TOP6 진입은 관심 대상을 찾는 단계입니다. 종목 판정은 결정실, 진입 타이밍은 트레이딩룸에서 확인합니다.</p>';}
function stockCard(id,target){const s=stocks[id],route=target||'decision',isHolding=id==='h';return '<a class="stock-card" href="#'+(isHolding?'chart':route)+'-'+id+'"><div><h3>'+s.name+'</h3><p class="meta">'+theme(s.theme).name+' · '+(isHolding?'보유 관리':s.representative?'대표 후보':'대표 미선정')+'</p>'+decisionBadge(id)+'</div><div class="stock-tags">'+badges(s.lanes)+'<small>'+(isHolding||route==='chart'?'차트':'판정')+' →</small></div></a>';}
function decisionList(){const keys=candidateIds.filter(id=>decisionFilter==='all'||decisions[id].status===decisionFilter);const filters=[['all','전체'],['buy','매수대상'],['hold','보류'],['excluded','제외'],['not-input','미입력']];return back('today','오늘로')+title('결정실 · 종목 심사','종목별 판정','판정의 이유와 다음 확인을 함께 봅니다.')+'<div class="decision-counts">'+filters.slice(1).map(f=>'<div><b>'+candidateIds.filter(id=>decisions[id].status===f[0]).length+'</b><span>'+f[1]+'</span></div>').join('')+'</div><p class="meta decision-date">'+ASOF+'</p><div class="filter-row decision-filters" aria-label="결정실 판정 선택">'+filters.map(f=>'<button data-decision-filter="'+f[0]+'" aria-pressed="'+(decisionFilter===f[0])+'">'+f[1]+'</button>').join('')+'</div><div class="decision-list">'+(keys.length?keys.map(id=>{const d=decisions[id],s=stocks[id];return '<article class="decision-card"><div class="card-top"><h2>'+s.name+'</h2>'+decisionBadge(id)+'</div><p class="meta">'+theme(s.theme).name+' · '+badges(s.lanes)+'</p><p>'+d.reason+'</p><p class="next-line"><b>다음 확인</b> · '+d.next+'</p><a class="text-link" href="#decision-'+id+'">판정 이유와 근거 보기 →</a></article>';}).join(''):'<div class="state-box"><p>이 가상 예시에는 해당 판정 종목이 없습니다.</p></div>')+'</div><details><summary>레인과 결정실의 관계</summary><p>A·B·C 레인 종목은 대표 여부와 별개로 심사 대상에 포함됩니다. D만 충족한 종목은 운영 대표로 선정됐는지 함께 확인합니다. 미입력·자료 미확인·제외 판정은 서로 다릅니다.</p></details><a class="text-link section" href="#manager">레인별 후보 다시 보기 →</a>';}
function decisionDetail(id){const s=stocks[id],d=decisions[id];if(!s||!d)return decisionList();const t=theme(s.theme);return back('decision','결정실 목록')+title('결정실 · 종목별 판정',s.name,'가상 심사 예시 · '+ASOF)+journey(3,id)+'<section class="decision-result"><div class="card-top">'+decisionBadge(id)+'<span>'+badges(s.lanes)+'</span></div><h2>'+d.headline+'</h2><p>'+d.reason+'</p></section><section class="section"><h2>이 종목을 보게 된 이유</h2><ul class="source-trail"><li><b>뉴스·테마</b><span>'+t.name+' · '+(s.theme==='cooling'?'↗ 돈몰림 추천테마':t.rank+'위 TOP6 주도테마')+'</span></li><li><b>펀드매니저실</b><span>'+s.lanes.join('·')+' 충족 · '+(s.representative?'대표 선정':'대표 미선정')+'</span></li><li><b>결정실 입력</b><span>'+(d.status==='not-input'?'D 단독 · 운영 대표 미선정으로 미입력':'심사 대상 · 결과 확인')+'</span></li></ul></section><div class="reading section"><section><h2>판정을 지지하는 근거</h2><p>'+d.support+'</p></section><section><h2>반대 근거·아직 모르는 것</h2><p>'+d.risk+'</p></section><section><h2>다음 확인</h2><p>'+d.next+'</p></section><details><summary>심사 근거 네 가지</summary><p>시장행동 · 실적 · 촉매 · 반대근거를 함께 확인합니다. 이 공개 예시는 판정의 읽는 순서를 보여주며, 실제 심사 수치는 연결하지 않았습니다.</p></details></div><section class="section"><h2>그럼 지금 살 때인가요?</h2><p>'+d.timing+'</p>'+(d.status==='buy'?'<a class="button section" href="#chart-'+id+'">트레이딩룸에서 매수 타이밍 확인 →</a>':'<a class="button secondary section" href="#chart-'+id+'">차트 참고 보기 · 매수대상 아님</a>')+'</section><div class="related-actions"><a class="text-link" href="#theme-'+s.theme+'">테마·돈몰림 근거 확인 →</a><a class="text-link" href="#manager">레인 조건과 대표 여부 →</a></div><section class="section"><h2>관련 기사 원문 맥락</h2>'+newsList(articles.filter(a=>a.company===id),'decision-'+id)+'</section>';}
function timingPanel(id){const d=decisions[id];if(!d)return '<div class="notice"><b>보유 관리</b> · 현재 종가와 추세를 확인합니다. 신규매수 심사 예시와 구분합니다.</div>';return '<section class="timing-panel"><div class="card-top"><span class="eyebrow">매수 타이밍 · 가상 예시</span>'+decisionBadge(id)+'</div><h2>'+(d.status==='buy'?'새 회복·돌파 신호 없음':'매수대상으로 선택되지 않음')+'</h2><p>'+(d.status==='buy'?'종목 심사는 통과했습니다. 지금 진입할 신호는 아직 확인되지 않았습니다.':d.status==='hold'?'결정실 보류 사유를 먼저 확인합니다. 차트가 좋아 보여도 보류를 해제하지 않습니다.':'결정실 미입력 상태입니다. 차트 참고만으로 심사 통과를 대신하지 않습니다.')+'</p><p class="next-line"><b>다음 확인</b> · '+(d.status==='buy'?'다음 종가에서 새 회복·돌파 조건과 기준 가격을 확인합니다.':d.next)+'</p><a class="text-link" href="#decision-'+id+'">이 종목의 결정실 판정 확인 →</a></section>';}
function trading(){return back('decision','결정실 목록')+title('트레이딩룸 · 신규매수','선택된 종목의<br>진입 타이밍을 확인해요.','결정실에서 매수대상으로 분류된 종목의 타이밍을 이어 봅니다.')+journey(4)+'<div class="cards">'+candidateIds.filter(id=>decisions[id].status==='buy').map(id=>stockCard(id,'chart')).join('')+'</div><p class="meta section">보류·제외·미입력 종목은 결정실에 남습니다. 신호 없음은 종목 탈락을 뜻하지 않습니다.</p><a class="button secondary section" href="#holdings">보유주식 관리로</a>'; }
function holdings(){return title('트레이딩룸 · 내 주식','보유 관리도<br>종목별로 차분하게.','실제 계좌·수량·평단을 넣지 않은 가상 예시입니다.')+'<div class="cards">'+stockCard('h','chart')+'</div><a class="button secondary section" href="#decision">신규 후보의 결정실 판정 보기</a>';}
function candidates(){return title('후보 · 결정실','후보를 모으고,<br>판정을 확인합니다.','선택된 종목은 트레이딩룸에서 진입 타이밍을 이어 봅니다.')+decisionSummary()+journey(3)+'<section class="section"><h2>종목별 현재 판정</h2>'+candidateIds.map(id=>stockCard(id)).join('')+'</section><div class="related-actions"><a class="button secondary" href="#manager">A·B·C·D 레인부터 확인</a><a class="text-link" href="#research">추천테마·TOP6 구성 종목 →</a></div>';}

function title(k,t,p){return '<div class="page-title"><div class="eyebrow">'+k+'</div><h1 tabindex="-1">'+t+'</h1>'+(p?'<p>'+p+'</p>':'')+'</div>';}
function back(h,t){return '<a class="back" href="#'+h+'">← '+t+'</a>';}
function badges(ids){return ids.map(l=>'<span class="lane-badge">'+l+'</span>').join(' ');}
function emptyData(){return state==='loading'||state==='error';}
function quick(h,name,text){return '<a class="daily-link" href="#'+h+'"><span class="pixel-mark" aria-hidden="true">✦</span><span><b>'+name+'</b><small>'+text+'</small></span><span aria-hidden="true">→</span></a>';}
function shop(){return '<div class="daily-scene"><a class="shop-picture" href="#space" aria-label="북두의 공간 보기"><img src="assets/entry-mobile-v2.webp" width="1774" height="887" alt="바닷가의 작은 북두 가게" fetchpriority="high"></a><div><div class="eyebrow">바닷가의 투자 이야기</div><h1 tabindex="-1">오늘의 북두</h1><p class="meta">'+ASOF+'</p><span class="shop-sign">'+star+' 반가워요, 오늘도</span></div></div>';}
function guide(){return '<button class="guide-bubble" type="button" data-guide aria-label="안내원의 짧은 팁 보기"><span class="guide-portrait" aria-hidden="true"></span><span><b>북두 안내원 <small>눌러서 팁 보기</small></b><span id="guide-message" aria-live="polite">'+guideLines[guideStep]+'</span></span><span class="guide-star" aria-hidden="true">'+star+'</span></button>';}
function newsList(items,from){return '<ul class="news-list">'+items.map(a=>'<li><a href="#article-'+a.id+'" data-origin="'+from+'"'+(readArticles.has(a.id)?' class="is-read"':'')+'><span class="news-meta"><span>'+a.time+' · '+theme(a.theme).name+'</span><span>'+a.kind+(readArticles.has(a.id)?' · 읽음':'')+'</span></span><span class="headline">'+a.title+'</span></a></li>').join('')+'</ul>';}
function home(){
 if(state==='loading')return title('오늘의 북두','새 자료를 확인하고 있어요.','')+'<div class="state-box" role="status"><div class="skeleton title"></div><div class="skeleton"></div><p>확인 전에는 변화 건수를 표시하지 않습니다.</p><button class="button secondary" data-normal>완료 화면 보기</button></div>';
 if(state==='error')return title('오늘의 북두','새 자료를 가져오지 못했어요.','')+'<div class="notice error" role="status">오늘의 변화와 뉴스 갱신 여부가 미확인입니다.</div><div class="state-box section"><button class="button" data-normal>다시 불러오기</button><a class="button secondary" href="?state=stale#today">마지막 자료 보기</a></div>';
 if(state==='empty')return '<div class="quiet-guide"><span class="guide-portrait" role="img" aria-label="북두 안내원"></span><div><b>북두 안내원</b><p>새 자료를 확인했어요.</p></div></div>'+title('오늘의 북두','새로 확인된 변화가 없어요.','뉴스와 순위 확인은 끝났습니다.')+'<div class="state-box"><p>새 뉴스 0건 · 신규 TOP6 진입 0건 · 레인 변화 0건인 가상 예시입니다.</p><a class="button" href="#holdings">내 주식과 차트 보기</a><p class="meta">확인 기준 · '+ASOF+'</p></div>';
 const stale=state==='stale'?'<div class="notice" role="status"><strong>이전 자료입니다.</strong> 아래 내용은 마지막 저장 자료이며 최신 갱신 여부는 미확인입니다.</div>':'';
 return shop()+stale+guide()+decisionSummary()+'<nav class="daily-links home-shortcuts" aria-label="판정 전 확인">'+quick('research','리서치센터','추천테마 · TOP6 종목')+quick('manager','펀드매니저실','A·B·C·D 후보')+'</nav><a class="text-link park-shortcut" href="#park">사장실 · 하루 순위와 주요 내용 →</a><section class="section home-news"><div class="section-head"><h2>오늘 뉴스 <small>'+articles.length+'</small></h2><a class="text-link" href="#themes">테마 비교 →</a></div><p class="meta section-intro">최신순 전체 제목 · 분석 대기 기사 포함</p>'+newsList(articles,'today')+'</section><section class="section"><div class="section-head"><h2>관심은 어디로?</h2><a class="text-link" href="#themes">비교 보기 →</a></div>'+'<p class="meta">주간 사건: 09/26–10/02 → 10/03–10/09<br>돈몰림·순위: 10/08 → 10/09 장 마감</p>'+themeCard(theme('grid'))+themeCard(theme('cooling'))+'</section><a class="daily-link section" href="#holdings"><span class="pixel-mark" aria-hidden="true">▥</span><span><b>내 주식과 차트</b><small>종가 · 25일선 · 추세와 다음 확인</small></span><span aria-hidden="true">→</span></a>';
}

function themeCard(t){const labels={rising:'관심 증가',steady:'현재 관심',cooling:'관심 감소'};return '<a class="theme-card" href="#theme-'+t.id+'"><div class="card-top"><span class="status">'+labels[t.trend]+'</span><span class="meta">가상 비교</span></div><h3>'+t.name+'</h3><div class="compare-line"><span>주간 사건</span><b>'+t.old+' → '+t.now+'건</b></div><div class="compare-line"><span>돈몰림</span><b>'+t.moneyOld.toFixed(1)+' → '+t.money.toFixed(1)+'배</b></div><div class="compare-line"><span>테마 순위</span><b>'+t.prev+' → '+t.rank+'위</b></div><p>'+t.reason+'</p><span class="card-action">변화 이유와 관련 종목 →</span></a>';}
function themesPage(){const filters=[['all','전체'],['steady','현재 관심'],['rising','관심 증가'],['cooling','관심 감소']];let items=themes.filter(t=>['grid','chip','cooling','defense'].includes(t.id)&&(themeFilter==='all'||t.trend===themeFilter));return back('today','오늘로')+title('테마뉴스 · 관심의 변화','지금의 관심과<br>다음 관찰 대상을 비교해요.','인기 예측을 확정하지 않고, 관심이 달라진 이유를 확인합니다.')+'<div class="period-note"><b>기사 사건 비교 · 같은 7일씩</b><span>이전 09/26–10/02 → 최근 10/03–10/09</span><small>중복 기사를 묶은 사건 수 · 가상 예시</small></div><div class="filter-row" aria-label="테마 관심 분류">'+filters.map(f=>'<button data-theme-filter="'+f[0]+'" aria-pressed="'+(themeFilter===f[0])+'">'+f[1]+'</button>').join('')+'</div><div class="cards">'+items.map(themeCard).join('')+'</div><div class="notice">주간 뉴스 관심과 10/08 → 10/09 장 마감 돈몰림·순위는 비교 기간이 다릅니다. 하나의 종합 인기 점수로 합치지 않습니다.</div>';}
function themeDetail(id){const t=theme(id);if(!t)return themesPage();const items=articles.filter(a=>a.theme===id);return back('themes','테마 비교 목록')+title('테마뉴스 · 가상 비교',t.name,'관심 증가와 실제 회사 영향을 구분해서 읽습니다.')+journey(1)+'<div class="reading"><section><h2>무엇이 달라졌나요?</h2><p>주간 사건 '+t.old+' → '+t.now+'건. '+t.reason+'</p><p class="meta">09/26–10/02 → 10/03–10/09 · 각 7일</p></section><section><h2>실제 돈도 움직였나요?</h2><p>가상 돈몰림 '+t.moneyOld.toFixed(1)+' → '+t.money.toFixed(1)+'배, 테마 '+t.prev+' → '+t.rank+'위.</p><p class="meta">10/08 → 10/09 장 마감 비교</p></section><section><h2>다음 확인</h2><p>'+t.next+'</p></section></div><section class="section"><h2>테마 구성 종목 · 레인과 판정</h2>'+(t.stocks.length?t.stocks.map(id=>stockCard(id)).join(''):'<p class="meta">이 테마의 구성 종목 예시는 아직 수록하지 않았습니다.</p>')+'</section><section class="section"><h2>오늘의 관련 제목</h2>'+(items.length?newsList(items,'theme-'+id):'<p class="meta">오늘의 연결 기사 예시는 없습니다.</p>')+'</section><a class="button secondary section" href="#research">리서치에서 TOP6 확인</a>';}

function manager(){const filters=['all','A','B','C','D'],keys=candidateIds.filter(id=>laneFilter==='all'||stocks[id].lanes.includes(laneFilter));return back('today','오늘로')+title('펀드매니저실','어떤 종목이<br>레인에 들어왔나요?','레인 조건과 대표 여부를 보고, 종목별 결정실 판정으로 이어갑니다.')+journey(2)+'<div class="lane-summary" aria-label="레인별 종목 수">'+['A','B','C','D'].map(l=>'<div><b>'+l+'</b><span>'+candidateIds.map(id=>stocks[id]).filter(s=>s.lanes.includes(l)).length+'종목</span></div>').join('')+'</div><div class="notice"><b>가상 변화</b> · 가상기업 C가 D 조건을 새로 충족했습니다.</div><div class="filter-row" aria-label="레인 선택">'+filters.map(l=>'<button data-lane="'+l+'" aria-pressed="'+(laneFilter===l)+'">'+(l==='all'?'전체':l+'레인')+'</button>').join('')+'</div><div class="cards">'+(keys.length?keys.map(id=>stockCard(id)).join(''):'<div class="state-box"><p>이 예시에는 '+laneFilter+'레인 충족 종목이 없습니다.</p></div>')+'</div><p class="meta section">중복 제외 3종목입니다. 가상기업 A는 B·D를 함께 충족하므로 레인별 수를 더하면 4가 됩니다. A·B·C는 대표 여부와 별개로 결정실 심사 대상이며, D만 충족한 경우 운영 대표 선정 여부를 확인합니다.</p><a class="button section" href="#decision">결정실에서 종목별 판정 확인 →</a>';}
function park(){return back('today','오늘로')+title('사장실 놀이공원','오늘의 변화를<br>작은 퍼레이드처럼.','전 거래일 → 현재 장 마감 자료의 비교입니다.')+'<div class="parade-banner" aria-hidden="true">'+star+'<span>오늘의 변화 기록</span>'+star+'</div><section><h2>테마 순위가 어떻게 달라졌나요?</h2><p class="meta">10/08 → 10/09 · 가상 자료</p><ul class="change-rows">'+['grid','cooling','defense','chip'].map(id=>{const t=theme(id);return '<li><a href="#theme-'+id+'"><b>'+t.name+'</b><span>'+t.prev+'위 → '+t.rank+'위</span><small>'+(t.prev>6&&t.rank<=6?'TOP6 진입':t.prev<=6&&t.rank>6?'TOP6 이탈':t.rank<t.prev?'순위 상승':'순위 유지')+'</small></a></li>';}).join('')+'</ul></section><section class="section"><h2>오늘의 주요 내용</h2><ul class="plain-list"><li>전력망 테마의 TOP6 진입을 확인합니다.</li><li>가상기업 C의 D레인 신규 충족을 확인합니다.</li><li>냉각 테마의 기사 관심과 돈몰림은 서로 다른 움직임입니다.</li></ul></section><section class="section"><h2>핵심 기사도 원문 맥락으로</h2>'+newsList([articles[1],articles[2]],'park')+'<a class="text-link" href="#news">오늘 뉴스 제목 전체 보기 →</a></section><div class="notice">시장 위험·매력의 실제 수치는 미연결입니다. 결정실의 가상 종목별 판정은 아래에서 확인할 수 있습니다.</div><a class="button secondary section" href="#decision">결정실 보기</a>';}
function news(){const items=newsFilter==='all'?articles:articles.filter(a=>a.kind==='분석 대기');return back('today','오늘로')+title('뉴스룸','제목부터 쭉 훑어보세요.','제목을 자르지 않고 시간순으로 보여줍니다.')+'<div class="filter-row" aria-label="뉴스 보기"><button data-news-filter="all" aria-pressed="'+(newsFilter==='all')+'">전체 '+articles.length+'</button><button data-news-filter="pending" aria-pressed="'+(newsFilter==='pending')+'">분석 대기 1</button></div>'+newsList(items,'news')+'<a class="button secondary section" href="#themes">테마별 관심 변화 비교</a>';}
function article(id){const a=articles.find(x=>x.id===id);if(!a)return news();readArticles.add(id);return back(origin,'읽던 목록으로')+title(theme(a.theme).name+' · '+a.kind,a.title,'')+'<p class="meta article-date">가상 기사 · '+a.time+' · '+ASOF+'</p><div class="reading"><section><h2>한눈에 요약</h2><p>'+a.summary+'</p></section><section><h2>확인된 것과 모르는 것</h2><p>'+(a.kind==='분석 대기'?'분석 대기 상태입니다. 제목만으로 회사 영향이나 방향을 판단하지 않습니다.':'이 문서는 화면 구성을 위한 가상 기사입니다. 운영에서는 기사에 적힌 사실과 아직 확인되지 않은 회사 영향을 분리합니다.')+'</p></section><section><h2>다음 확인</h2><p>'+theme(a.theme).next+'</p></section><details><summary>원문·출처</summary><p>가상 기사이므로 실제 원문 링크는 없습니다. 운영 연결 때 기사 원문과 게시 시각을 표시합니다.</p></details></div><div class="related-actions"><a class="button secondary" href="#theme-'+a.theme+'">이 테마의 관심 변화</a>'+(a.company?'<a class="button secondary" href="#decision-'+a.company+'">관련 종목 판정 보기</a>':'<p class="meta">회사 연결이 확인되지 않은 업종 기사입니다.</p>')+'</div>';}
const prices=[];let day=new Date(Date.UTC(2026,9,9));while(prices.length<60){if(day.getUTCDay()!==0&&day.getUTCDay()!==6)prices.unshift({date:day.toISOString().slice(5,10)});day.setUTCDate(day.getUTCDate()-1);}prices.forEach((p,i)=>{p.close=Math.round(1100+i*3+Math.sin(i/4)*15);p.volume=12+(i*7%19);p.ma=i<24?null:prices.slice(i-24,i+1).reduce((a,x)=>a+x.close,0)/25;});
function chartSVG(id){const s=stocks[id],visible=prices.slice(-chartPeriod),all=visible.flatMap(p=>[p.close+s.offset,p.ma==null?null:p.ma+s.offset]).filter(x=>x!==null),lo=Math.floor((Math.min(...all)-15)/20)*20,hi=Math.ceil((Math.max(...all)+15)/20)*20;
const x=i=>8+i/(visible.length-1)*284,y=v=>166-(v-lo)/(hi-lo)*150;
const close=visible.map((p,i)=>(i?'L':'M')+x(i).toFixed(1)+','+y(p.close+s.offset).toFixed(1)).join(' ');let ma='',begun=false;visible.forEach((p,i)=>{if(p.ma!=null){ma+=(begun?'L':'M')+x(i).toFixed(1)+','+y(p.ma+s.offset).toFixed(1)+' ';begun=true;}});
const index=Math.max(60-chartPeriod,Math.min(59,chartIndex)),point=prices[index];chartIndex=index;const selectedX=x(index-(60-chartPeriod));
return '<figure class="price-figure"><div class="chart-legend"><span><i class="legend-close"></i>종가</span><span><i class="legend-ma"></i>25일선</span><span>가상 가격 · 엔</span></div><div class="price-plot"><svg viewBox="0 0 300 180" role="img" aria-label="가상 종가와 25일 이동평균선. 아래 날짜 선택과 수치 표로 확인할 수 있습니다."><path d="M0 16H300M0 91H300M0 166H300" stroke="#d9ded7" fill="none"/><path d="'+ma+'" stroke="#58686b" stroke-width="2" stroke-dasharray="5 4" fill="none"/><path d="'+close+'" stroke="#205b62" stroke-width="3" fill="none"/><line x1="'+selectedX+'" x2="'+selectedX+'" y1="8" y2="174" stroke="#b38c44"/><circle cx="'+selectedX+'" cy="'+y(point.close+s.offset)+'" r="4" fill="#205b62"/></svg><div class="price-axis"><span>'+hi.toLocaleString()+'</span><span>'+((hi+lo)/2).toLocaleString()+'</span><span>'+lo.toLocaleString()+'</span></div></div><div class="chart-dates"><span>'+visible[0].date+'</span><span>'+visible[visible.length-1].date+'</span></div><div class="volume-head"><b>거래량</b><span>가상 · 만 주</span></div><svg class="volume-chart" viewBox="0 0 300 55" role="img" aria-label="가상 거래량 막대 차트">'+visible.map((p,i)=>'<rect x="'+Math.max(0,x(i)-2)+'" y="'+(52-p.volume)+'" width="'+(chartPeriod===20?6:3)+'" height="'+p.volume+'" fill="#205b62" opacity=".48"/>').join('')+'</svg><figcaption>기간은 표시 범위만 바꿉니다. 25일선의 계산 기간은 같습니다.</figcaption></figure>';
}
function readout(id){const p=prices[chartIndex],o=stocks[id].offset;return '<b>'+p.date+' · 선택한 날짜</b><span>종가 '+(p.close+o).toLocaleString()+'엔</span><span>25일선 '+(p.ma==null?'자료 부족':Math.round(p.ma+o).toLocaleString()+'엔')+'</span><span>거래량 '+p.volume+'만 주</span>';}
function chart(id){const s=stocks[id];if(!s)return holdings();const last=prices[59],prev=prices[58],above=last.close>last.ma,priorAbove=prev.close>prev.ma;return back(id==='h'?'holdings':'decision-'+id,id==='h'?'내 주식 목록':'이 종목의 결정실 판정')+title('트레이딩룸 · '+(id==='h'?'보유 관리':'신규매수 타이밍'),(id==='h'?'보유 종목의<br>흐름을 확인해요.':'선택한 종목,<br>지금 진입할 때인가요?'),'가상 화면 예시 · 실제 매매 판정은 미연결입니다.')+(id==='h'?'':journey(4,id))+'<label class="stock-select">종목 선택<select id="stock-control"><option value="a"'+(id==='a'?' selected':'')+'>가상기업 A · 매수대상</option><option value="b"'+(id==='b'?' selected':'')+'>가상기업 B · 보류</option><option value="c"'+(id==='c'?' selected':'')+'>가상기업 C · 미입력</option><option value="h"'+(id==='h'?' selected':'')+'>가상 보유기업 H · 보유 관리</option></select></label><div class="stock-title"><h2>'+s.name+'</h2><div>'+badges(s.lanes)+'</div></div><p class="meta">'+theme(s.theme).name+' · '+ASOF+'</p>'+timingPanel(id)+'<div class="filter-row" aria-label="차트 표시 기간"><button data-period="20" aria-pressed="'+(chartPeriod===20)+'">1개월 · 20거래일</button><button data-period="60" aria-pressed="'+(chartPeriod===60)+'">3개월 · 60거래일</button></div><div id="chart-panel">'+chartSVG(id)+'</div><label class="range-label" for="chart-date">날짜를 움직여 수치 확인</label><input class="date-range" id="chart-date" type="range" min="'+(60-chartPeriod)+'" max="59" value="'+chartIndex+'" aria-valuetext="'+prices[chartIndex].date+' 종가 '+(prices[chartIndex].close+s.offset)+'엔"><div class="chart-readout" id="chart-readout" aria-live="polite">'+readout(id)+'</div><div class="reading section"><section><span class="status muted">마지막 종가 기준 · 가상 분석</span><h2 class="analysis-heading">'+(above?'25일선 위에서 흐름을 확인 중':'25일선 아래에서 흐름을 확인 중')+'</h2><p><b>현재 상태</b> · 종가 '+(last.close+s.offset).toLocaleString()+'엔 / 25일선 '+Math.round(last.ma+s.offset).toLocaleString()+'엔.</p><p><b>이유</b> · '+(above&&priorAbove?'전일에도 25일선 위였습니다. 선 위에 있다는 이유만으로 새 회복 신호라고 부르지 않습니다.':'위치와 전일 상태를 함께 확인합니다.')+'</p><p><b>다음 확인</b> · 다음 종가의 선 유지 여부와 관련 회사 뉴스를 확인합니다.</p></section><section><h2>차트 해석의 기준</h2><p>종가가 25일선 위에 있어도 새 회복·돌파 신호가 있다는 뜻은 아닙니다. 이 예시의 결정실 판정은 시연용이며 선 그래프에서 계산하지 않습니다. 볼린저는 효과 미검증 참고로 구분합니다.</p></section></div><details class="chart-table"><summary>가격 수치를 표로 보기</summary><table><thead><tr><th>날짜</th><th>종가(엔)</th><th>25일선(엔)</th></tr></thead><tbody>'+prices.slice(-5).map(p=>'<tr><td>'+p.date+'</td><td>'+(p.close+s.offset).toLocaleString()+'</td><td>'+Math.round(p.ma+s.offset).toLocaleString()+'</td></tr>').join('')+'</tbody></table><p class="meta">최근 5거래일 · 모두 가상 수치</p></details><div class="related-actions"><a class="button secondary" href="#theme-'+s.theme+'">관련 테마·뉴스 확인</a><a class="text-link" href="#'+(id==='h'?'decision':'decision-'+id)+'">결정실의 근거 확인 →</a></div>';}


function records(){return title('돌아보기 서가','같은 기준으로<br>지난 판단을 돌아봐요.','성과기록과 선정성적은 서로 다른 항목입니다.')+'<ul class="room-list"><li><a href="#performance"><span>성과기록<small>판단 이후의 결과와 평가 대기</small></span><span>→</span></a></li><li><a href="#selection"><span>선정성적<small>선정 종목과 비교 기준</small></span><span>→</span></a></li><li><a href="#park"><span>하루의 변화<small>사장실 놀이공원</small></span><span>→</span></a></li></ul>';}
function space(){return back('rooms','전체로')+title('공간 보기','바닷가의 작은 북두.','가게에서 오늘의 변화를 만나고, 라운지에서 자세히 읽습니다.')+'<figure class="entry-art"><img src="assets/entry-mobile-v2.webp" width="1774" height="887" alt="북두 가게의 왼쪽 장면"></figure><figure class="space-art"><img src="assets/lounge-mobile-v2.webp" width="1000" height="500" alt="안내원이 있는 북두 라운지"><figcaption>그림은 작은 휴식, 글자는 또렷하게.</figcaption></figure><a class="button section" href="#today">오늘의 북두로</a>';}
function allrooms(){return title('전체 방','어느 방으로 갈까요?','기존 방 이름을 그대로 찾아갈 수 있습니다.')+'<a class="space-link text-link" href="#space">'+star+' 북두의 공간 보기 →</a><ul class="room-list">'+rooms.map(r=>'<li><a href="#'+r[0]+'"><span>'+r[1]+'<small>'+r[2]+'</small></span><span aria-hidden="true">→</span></a></li>').join('')+'</ul>';}
function generic(k){const names={decision:'결정실',signals:'BNF 신호실',performance:'성과기록',selection:'선정성적'};return back(k==='performance'||k==='selection'?'records':'rooms','목록으로')+title('기존 기능 유지',names[k],'기존 계산 결과와 근거를 연결할 화면입니다.')+'<div class="reading"><section><h2>현재 상태 · 미연결</h2><p>이 시안에는 실제 판정·성과 수치가 없습니다.</p></section><section><h2>이유와 반대 근거</h2><p>운영 프로그램의 원래 결과를 표시하고, 없는 근거를 새로 만들지 않습니다.</p></section><section><h2>다음 확인</h2><p>자료 기준일, 충족 여부, 원문을 함께 확인합니다.</p></section></div>'+(k==='decision'?'<a class="button secondary section" href="#park">사장실 놀이공원의 하루 변화</a>':'');}
function active(k){if(['today','news','themes','research','park'].includes(k)||k.startsWith('article-')||k.startsWith('theme-'))return'today';if(k==='holdings'||k==='chart-h')return'holdings';if(['candidates','manager','decision','trading','chart-a','chart-b','chart-c'].includes(k)||k.startsWith('decision-'))return'candidates';if(['records','performance','selection'].includes(k))return'records';return'rooms';}
function render(keepScroll){let k=location.hash.slice(1)||'today';if(k==='main-content')k=current||'today';k=aliases[k]||k;let html='';if(k==='today')html=home();else if(k==='research')html=research();else if(k==='manager')html=manager();else if(k==='decision')html=decisionList();else if(k.startsWith('decision-'))html=decisionDetail(k.slice(9));else if(k==='park')html=park();else if(k==='themes')html=themesPage();else if(k.startsWith('theme-'))html=themeDetail(k.slice(6));else if(k==='news')html=news();else if(k.startsWith('article-'))html=article(Number(k.slice(8)));else if(k.startsWith('chart-'))html=chart(k.slice(6));else if(k==='holdings')html=holdings();else if(k==='trading')html=trading();else if(k==='candidates')html=candidates();else if(k==='records')html=records();else if(k==='rooms')html=allrooms();else if(k==='space')html=space();else if(['decision','signals','performance','selection'].includes(k))html=generic(k);else{k='today';html=home();}
 main.innerHTML=html+'<p class="hint">가상 자료로 보는 화면 시안입니다.<br><a href="plan.html" target="_top">기획서로 돌아가기 →</a></p>';document.querySelectorAll('[data-nav]').forEach(a=>{if(a.dataset.nav===active(k))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});current=k;document.title=(k==='today'?'오늘의 북두':main.querySelector('h1').textContent)+' · 북두 모바일 예시';if(!keepScroll){main.querySelector('h1')?.focus({preventScroll:true});window.scrollTo(0,positions[k]||0);}updateNav();}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(a){positions[current]=window.scrollY;if(a.dataset.origin)origin=a.dataset.origin;}const b=e.target.closest('button');if(!b)return;
 if(b.hasAttribute('data-normal')){state='normal';render();}
 if(b.hasAttribute('data-guide')){guideStep=(guideStep+1)%guideLines.length;document.getElementById('guide-message').textContent=guideLines[guideStep];b.classList.remove('greet');void b.offsetWidth;b.classList.add('greet');}
 if(b.dataset.themeFilter){themeFilter=b.dataset.themeFilter;render(true);main.querySelector('[data-theme-filter="'+themeFilter+'"]').focus({preventScroll:true});}
 if(b.dataset.newsFilter){newsFilter=b.dataset.newsFilter;render(true);main.querySelector('[data-news-filter="'+newsFilter+'"]').focus({preventScroll:true});}
 if(b.dataset.lane){laneFilter=b.dataset.lane;render(true);main.querySelector('[data-lane="'+laneFilter+'"]').focus({preventScroll:true});}
 if(b.dataset.decisionFilter){decisionFilter=b.dataset.decisionFilter;render(true);main.querySelector('[data-decision-filter="'+decisionFilter+'"]').focus({preventScroll:true});}
 if(b.dataset.period){chartPeriod=Number(b.dataset.period);render(true);main.querySelector('[data-period="'+chartPeriod+'"]').focus({preventScroll:true});}
});
document.addEventListener('change',e=>{if(e.target.id==='stock-control')location.hash='chart-'+e.target.value;});
document.addEventListener('input',e=>{if(e.target.id!=='chart-date')return;chartIndex=Number(e.target.value);const id=current.slice(6);document.getElementById('chart-panel').innerHTML=chartSVG(id);document.getElementById('chart-readout').innerHTML=readout(id);e.target.setAttribute('aria-valuetext',prices[chartIndex].date+' 종가 '+(prices[chartIndex].close+stocks[id].offset)+'엔');});
function updateNav(){document.documentElement.style.setProperty('--nav-space',(document.querySelector('.bottom-nav').getBoundingClientRect().height+8)+'px');}
const toggle=document.getElementById('read-toggle');function setZoom(){document.documentElement.style.fontSize=16*zoom+'px';toggle.setAttribute('aria-pressed',String(zoom>1));toggle.textContent=zoom>1?'가 −':'가 +';toggle.setAttribute('aria-label',zoom>1?'기본 글자 크기로 보기':'글자 크게 보기');updateNav();}toggle.addEventListener('click',()=>{zoom=zoom>1?1:1.125;setZoom();});
window.addEventListener('hashchange',()=>render());window.addEventListener('resize',updateNav);setZoom();render();if(typeof ResizeObserver!=='undefined')new ResizeObserver(updateNav).observe(document.querySelector('.bottom-nav'));
})();
